version: "3.8"
services:
  d4:
    image: dillonad/d4bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: d4
    environment:
      D4BOT_DISCORDTOKEN: ${BOT_TOKEN}
      D4BOT_OTELENDPOINT: ${OTEL_ENDPOINT}