version: "3.8"
services:
  d4:
    image: dillonad/d4bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: d4
    environment:
      OTEL_ENDPOINT: jaeger-ui:4317
      OTEL_EXPORTER_INSECURE: "true"
      BOT_TOKEN: ${BOT_TOKEN}
    networks:
      - d4bot
    depends_on:
      - jaeger-ui

  jaeger-ui:
    container_name: jaeger-ui
    image: docker.io/jaegertracing/all-in-one
    ports:
      - "16686:16686"
    networks:
      - d4bot

networks:
  d4bot: