receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:

  jaeger:
    endpoint: jaeger-ui:14250
    tls:
      insecure: true

  logging:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
